DamyanBG/real-estate-react-app

src/App.js
src/components/Homes/AllHomes.js
src/components/Homes/HomeDetails.js
src/components/Homes/Homes.scss

home details page

---

src/components/Header/Header.js
src/components/Header/Header.scss

Issue #26 
Resolved using Link imported from react-router-dom
https://user-images.githubusercontent.com/103564105/209540421-7cb080a1-29c7-47e2-9b6e-ffe89a9fe06b.mp4

Route to Home page added

---

src/App.js
src/components/Header/Header.js
src/components/Rent/Rent.js

Rent Page has been updated
Issue #30 solved

Rent Page added

---

src/App.js
src/App.scss
src/components/User/SignInPage.js

- I have set the cookie to expire after 1 day.
- Cookies set by backend are much more secure. You should consider setting httpOnly cookie from backend. Maybe something to look at in future. 
- I believe the status code for wrong username and/or password should be 401.  Currently it is 400. 400 should be used if request is improper (for ex - wrong body).

Added signin route, component, and integrated with login be

---

src/components/Header/Header.scss

Fix the 'Rent' link color blue to black.
Issue #49 solved.

Fix Rent link color

---

src/App.js
src/common/fields.js
src/common/urls.js
src/components/User/Profile.js

Implemented profile page from #32

profile page

---

src/App.js
src/components/User/ChangePassword.js
src/components/User/Profile.js

I made change password page #45

change password page

---

src/App.js
src/components/Homes/ChangeEmail.js

I implemented change email page from #46

Change email page

---

src/components/Header/Header.js

add link to signup

---

src/components/HomePage/HomePage.js

This change resolves #57  by defining as key the atribute _id of every home

Unique key

---

src/App.scss
src/common/FormSubmitButton.js
src/common/InputFormRow.js
src/components/Header/Header.scss

i restyled user interface of the signup page. though some other pages were affected but i will be fixing the styles bit by bit for easy merging.

i restyled the signup page

---

src/App.scss
src/components/User/SignInPage.js

i restyled the sign in page for better user interface

restyled signin page

---

src/App.js
src/components/Header/Header.js
src/components/User/SignInPage.js
src/context/UserContext.js

make user context logic and tweak header

---

src/App.js
src/common/fields.js
src/components/Land/CreateLand.js

create land form

---

src/components/Rent/Rent.js
src/components/Rent/Rent.scss

Rent Page updated

---

src/App.js
src/components/Header/Header.js

On the header, I added a link to /link-meetings. Used some icons for the link. And I placed the icon on the left side of the chat icon in the header.

Real estate react app meeting link

---

src/components/HomePage/HomePage.js
src/components/HomePage/HomePage.scss

On the main page, there is a mapping of 4 homes. Every home has a photo and the corners are rounder. I made the bottom corners of the photo not to be rounded. And also added an alt prop and gave the alt prop the descriptive name "Home".

Fixed the photo showing bug

---

src/components/Homes/HomeDetails.js
src/components/Land/LandDetails.js

request meeting buttons

---

src/common/InputFormRow.js
src/common/fields.js
src/components/User/SignUpPage.js
src/components/User/components/AdminForm.js

Did the required changes as per the instruction for issue #146 .
The issue of the form getting submit even if there are more than 150 characters in fields is solved.
Validation logic is implemented in a more generic way because of which the admin_create form also gets validated, however, if we want to change the max and minimum character length for AdminForm.js then that can also be done separately through another commit.
Hope the changes are helpful!

Improve Validation

---

package.json
src/common/FormSubmitButton.js
src/common/InputFormRow.js
src/common/formikFile.js
src/components/Homes/CreateHome.js
src/components/Homes/EditHome.js
src/components/Homes/Homes.scss

Added form validations to the create-home and edit-home forms.

Added validations to the home form

---

src/common/InputFormRow.js
src/components/User/SignUpPage.js
src/components/User/components/AdminForm.js

Solved the issue of form getting submit with empty fields

Review Changes3

---

src/App.scss
src/common/InputFormRow.js
src/common/fields.js
src/common/utils.js
src/common/validation.js
src/components/User/SignUpPage.js

refactor validation of signup

---

src/components/News/NewsList.js
src/components/News/NewsList.scss

Deleted the News header as I felt it was just taking up room. Deleted the max width and set the text to fill the container.
If you would like any extra changes please let me know.

updated styles for news page

---

src/components/Header/Header.js
src/components/Header/Header.scss

I changed the styles for home and sell in the header

changed the styles for sell and buy in the header

---

README.md
src/App.js
src/components/About/About.js
src/components/About/About.scss
src/components/Header/Header.js

This PR adds an About page and also adds an link to the about page from the homepage. It also tries to slightly improve the README documentation.
closes #15 
As requested, I have added links to front-end repo, back-end repo and the youtube video. The following is a screenshot of the page I created.
Kindly review and let me know your thoughts. Thanks!

adds about page and a link for same in homepage. Improves Readme file.

---

package.json
public/index.html
src/components/Homes/HomeDetails.js
src/components/Homes/Homes.scss
src/components/Land/LandDetails.js

map to the details

---

src/components/visitations/CreateVisitation.js

Visitation works only with homeId. I made it work with landId too.

worked on making /create-visitation work for landId

---

package.json
src/components/Chat/Chat.js

This PR contains improvements  that prevent empty messages from being sent

Bug Fix for Empty chat Being Sent

---

src/components/visitations/CreateVisitation.js

create visitations refactoring

---

src/common/VisitationsTable.js
src/components/Homes/HomeDetails.js
src/components/Land/LandDetails.js

display visitations

---

src/components/Header/Header.js
src/components/Header/Header.scss

Fix: https://github.com/DamyanBG/real-estate-react-app/issues/231
Made it so that hovering on the items makes the drop-down appear but clicking them makes it go away. I felt the transition time was too high so reduced that. Changed the width of the drop-down menu to fit the content better.

Fixed the buy and sell dropdown menu

---

package.json
src/components/Homes/AllHomes.js
src/components/Homes/AllHomes.scss
src/components/Land/AllLands.js
src/components/Land/AllLands.scss

Task for **Pagination #232** Completed
1. Created state variables to manage pagination flow
2. Implemented pagination buttons and functions using React Paginate library
3. Provided class names for the buttons to make it easy for other developers to style them
4. Had to create a new stylesheet for Lands page to edit buttons
5. Made minor styles to pagination buttons but can be improved later

Pagination set for Lands and Homes Page

---

src/components/Homes/AllHomes.js
src/components/Land/AllLands.js

Issue #240 fixed - Pagination not shown for lesser entries

---

src/components/Header/Header.js

fixed sign-in issue

---

src/components/Land/CreateLand.js
src/components/Land/CreateLand.test.js

I made 2 unit tests for CreateLand #217

unit tests create land

---

src/components/Land/CreateLand.test.js

more tests

---

.dockerignore
Dockerfile
README.md

better docker support

---

.dockerignore
.gitignore
e2e-run-tests.js

add script for e2e run testing

---

src/components/Meeting/EditMeeting.jsx

changes made based on suggestions from previous PR

edit meeting fix

---

src/components/Homes/CreateHome.jsx
src/components/Homes/usePostHome.jsx

Disable button after submit #267 solved.

form submit button disabled on api loading in CreateHome.js

---

src/components/Homes/CreateHome.jsx
src/components/Homes/usePostHome.jsx

#319 I fixed the creation of the home + added message if some bad word is user. Further refactoring will be implemented

fix create home

---

src/reference/LandingPage.jsx
src/reference/reference.scss

code reference for langing page

---

src/App.scss

I updated the App.scss file in order to change the styling of the textarea in the /create-home page
Issue: #364

Textarea styling

---

src/components/Homes/AllHomes.jsx

message for long loading

---

src/common/homesApi.jsx
src/components/Homes/AllHomes.jsx
src/components/Homes/AllHomes.scss
src/components/common/HomeCard.jsx

home row styling

---

src/components/cards/home-cards/HomeCard.jsx
src/components/cards/home-cards/RoundedHomeCard.jsx
src/components/image/HomeImage.jsx
src/pages/home-pages/HomeDetails.jsx

create home image component
